[package]
name = "rust_calc"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_calc"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
statrs = "0.17"
